prev_category = ["shift+tab"]
next_category = ["tab"]

prev_item = ["up", "k"]
next_item = ["down", "j"]
prev_page = ["left", "h"]
next_page = ["right", "l"]
open_comments = ["enter", "space"]
open_comments_fullscreen = ["shift+enter"]

close_comments = ["esc"]
toggle_fullscreen = ["shift+enter"]
toggle_sub_comments = ["enter", "space"]
select_parent = ["left", "h"]
prev_comment = ["up", "k"]
next_comment = ["down", "j"]
prev_sibling_comment = ["p"]
next_sibling_comment = ["n"]

refresh = ["r"]
open_hn_in_browser = ["o"]
open_comment_in_browser = ["ctrl+o"]
open_domain_in_browser = ["O"]
go_to_start = ["home", "g"]
go_to_end = ["end", "G"]
quit = ["ctrl+c", "q"]